apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-webui
  labels:
    app: ollama-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-webui
  template:
    metadata:
      labels:
        app: ollama-webui
    spec:
      containers:
      - name: ollama-webui
        #image: ghcr.io/ollama-webui/ollama-webui:main
        image: ollamawebui/ollama-webui
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: OLLAMA_API_BASE_URL
          value: "http://ollama-service-internal:11433"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: ollama-webui-service
spec:
  selector:
    app: ollama-webui
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 32200
  type: NodePort
